print("nhap du lieu trong python ta có ham input()")
print("moi ban nhap vao cai gi day")
a = input()
print("ban vua nhap la : ",a)
print(type(a))
#con neu muon nhap kieu so nguyen hoac gì đo ta can ep kieu
print("moi ban nhap vao so ban thich")
b = int(input())
print("so ban vua nhap la: ",b)
print(type(b))
